---
- name: install EPEL repo
  become: true
  ansible.builtin.yum: 
    name: epel-release 
    state: present
- name: Install nginx for yum family
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx
- name: Create general config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: reload-nginx